name: Build and Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Lambda function
        run: |
          go mod download
          GOOS=linux go build -o main

      - name: Deploy Lambda function
        uses:  einaregilsson/aws-lambda-deploy@v1
        with:
          function-name: golangapp
          zip-file: main.zip
          aws-region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
